{
 "title": "Overload",
 "description": "Overload dashboard for yandex tank",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "RPS",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "overall_meta",
     "select": [
      [
       { "params": [ "RPS" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Success responses",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "proto_codes",
     "select": [
      [
       { "params": [ "200" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Fail responses",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "proto_codes",
     "select": [
      [
       { "params": [ "0" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Threads",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "overall_meta",
     "select": [
      [
       { "params": [ "active_threads" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "RPS",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "overall_meta",
     "select": [
      [
       { "params": [ "RPS" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Response Times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "ms", "label": "Time" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "overall_quantiles",
     "select": [
      [
       { "params": [ "q100" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       },
       { "params": [ "q100" ], "type": "alias" }
      ],
      [
       { "params": [ "q99" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "q99" ], "type": "alias" }
      ],
      [
       { "params": [ "q98" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "q98" ], "type": "alias" }
      ],
      [
       { "params": [ "q95" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "q95" ], "type": "alias" }
      ],
      [
       { "params": [ "q90" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "q90" ], "type": "alias" }
      ],
      [
       { "params": [ "q85" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "q85" ], "type": "alias" }
      ],
      [
       { "params": [ "q80" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "q80" ], "type": "alias" }
      ],
      [
       { "params": [ "q75" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "q75" ], "type": "alias" }
      ],
      [
       { "params": [ "q50" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "q50" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "overall_meta",
     "select": [
      [
       { "params": [ "RPS" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "RPS" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Net codes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net_codes",
     "select": [
      [
       { "params": [ "0" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "net_0" ], "type": "alias" }
      ],
      [
       { "params": [ "110" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "net_110" ], "type": "alias" }
      ],
      [
       { "params": [ "104" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "net_104" ], "type": "alias" }
      ],
      [
       { "params": [ "OK" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "OK" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "RPS",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "overall_meta",
     "select": [
      [
       { "params": [ "RPS" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "HTTP codes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "proto_codes",
     "select": [
      [
       { "params": [ "200" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "http_200" ], "type": "alias" }
      ],
      [
       { "params": [ "404" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "http_404" ], "type": "alias" }
      ],
      [
       { "params": [ "500" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "http_500" ], "type": "alias" }
      ],
      [
       { "params": [ "504" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "http_504" ], "type": "alias" }
      ],
      [
       { "params": [ "301" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "http_301" ], "type": "alias" }
      ],
      [
       { "params": [ "302" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "http_302" ], "type": "alias" }
      ],
      [
       { "params": [ "0" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "http_0" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "RPS",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "overall_meta",
     "select": [
      [
       { "params": [ "RPS" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}